### ISSUE TITLE
Use mockup to create basic version of the website for desktops

### ISSUE THREAD

**Issue by sitek94** [wieslaw-transport/wieslaw-trans.com#5]
* [mockup](https://preview.webflow.com/preview/wieslaw-transport?utm_medium=preview_link&utm_source=designer&utm_content=wieslaw-transport&preview=78736f882d404d77ace2e1b11570ef19&workflow=preview)
* desktops only

**Subtasks**

- [x] create "Navbar" component
- [x] create "Hero" section
- [x] add images:
  - [x] hero
  - [x] inside 
  - [x] distant
- [x] create "About us" section
- [x] create "Services" section
- [x] create "Contact" section
- [x] create "Footer"

**Comment by sitek94** [comment]
The basic version is done and is already available at:

https://wieslaw-trans.com
